In [1]:
from pingouin import ancova
import pandas as pd
import numpy as np
data3 = pd.DataFrame({'methodology': np.repeat(['Low-Carb', 'Mediterranean', 'Vegan'], 4),
                    'pre_diet_weight': [160, 170, 155, 165,
                                      170, 175, 160, 180,
                                      175, 180, 165, 170],
                    'post_diet_weight': [150, 160, 145, 155,
                                       155, 160, 150, 165,
                                       160, 165, 155, 160]})
data3

      methodology  pre_diet_weight  post_diet_weight
0        Low-Carb              160               150
1        Low-Carb              170               160
2        Low-Carb              155               145
3        Low-Carb              165               155
4   Mediterranean              170               155
5   Mediterranean              175               160
6   Mediterranean              160               150
7   Mediterranean              180               165
8           Vegan              175               160
9           Vegan              180               165
10          Vegan              165               155
11          Vegan              170               160

In [2]:
ancova(data=data3, dv='post_diet_weight', covar='pre_diet_weight', between='methodology')

            Source          SS  DF           F     p-unc       np2
0      methodology    6.734513   2    1.369732  0.307914  0.255084
1  pre_diet_weight  280.333333   1  114.033898  0.000005  0.934444
2         Residual   19.666667   8         NaN       NaN       NaN