In [5]:
from pingouin import ancova
import pandas as pd
import numpy as np
data2 = pd.DataFrame({'methodology': np.repeat(['Social Media Ads', 'Email Marketing', 'TV Commercials'], 4),
                    'pre_campaign_sales': [12000, 14000, 11000, 13000,
                                          13500, 12500, 11500, 14000,
                                          14200, 13000, 12000, 13800],
                    'post_campaign_sales': [15000, 16000, 13000, 14500,
                                           15500, 14500, 13500, 16000,
                                           16000, 15000, 14000, 15500]})

data2

         methodology  pre_campaign_sales  post_campaign_sales
0   Social Media Ads               12000                15000
1   Social Media Ads               14000                16000
2   Social Media Ads               11000                13000
3   Social Media Ads               13000                14500
4    Email Marketing               13500                15500
5    Email Marketing               12500                14500
6    Email Marketing               11500                13500
7    Email Marketing               14000                16000
8     TV Commercials               14200                16000
9     TV Commercials               13000                15000
10    TV Commercials               12000                14000
11    TV Commercials               13800                15500

In [4]:
ancova(data=data, dv='post_campaign_sales', covar='pre_campaign_sales', between='methodology')

AttributeError: 'function' object has no attribute 'ancova'